/**
 * QueUp — Queue Intelligence Engine
 *
 * Calculates estimated wait time, ticket number, congestion level,
 * and whether a branch is at capacity.
 *
 * Parameters calibrated from ML training (GradientBoosting, R²=0.9981):
 *   ml/wait_predictor.json  — generated by ml/train_wait_predictor.py
 */
import { Branch } from './firestore-schema';

// ── ML-calibrated parameters ───────────────────────────────────────────────
const ML_PARAMS = {
  avgServiceTimeMinutes: 3.59,     // learned from SA queue dataset
  peakMorningMultiplier: 1.208,    // 09:00–11:00
  peakAfternoonMultiplier: 1.116,  // 13:00–15:00
  busyDayMultiplier: 1.085,        // Monday (0) & Friday (4)
  peakMorningHours: [9, 10, 11],
  peakAfternoonHours: [13, 14, 15],
  busyDays: [0, 4],                // 0=Mon, 4=Fri
} as const;

export interface QueueIntelligenceResult {
  estimatedWaitMinutes: number;
  ticketNumber: string;
  congestionLevel: 'LOW' | 'MODERATE' | 'HIGH' | 'FULL';
  position: number;
  isFull: boolean;
  tfliteWaitPrediction: number; // placeholder until Android edge model runs
}

/**
 * Core heuristic engine.
 * Formula: waitTime = queueSize × avgServiceTime × congestion_multiplier
 */
export function computeQueueIntelligence(
  branch: Branch,
  existingTicketCount: number
): QueueIntelligenceResult {
  const position = existingTicketCount + 1;
  const isFull = branch.currentQueue >= branch.capacity;

  // Dynamic congestion level
  const loadRatio = branch.currentQueue / branch.capacity;
  let congestionLevel: 'LOW' | 'MODERATE' | 'HIGH' | 'FULL';
  let congestionMultiplier: number;

  if (isFull || loadRatio >= 1) {
    congestionLevel = 'FULL';
    congestionMultiplier = 1.5;
  } else if (loadRatio >= 0.7) {
    congestionLevel = 'HIGH';
    congestionMultiplier = 1.3;
  } else if (loadRatio >= 0.4) {
    congestionLevel = 'MODERATE';
    congestionMultiplier = 1.1;
  } else {
    congestionLevel = 'LOW';
    congestionMultiplier = 1.0;
  }

  // Time-of-day multiplier — from ML-calibrated parameters
  const now = new Date();
  const hour = now.getHours();
  const dow  = now.getDay() === 0 ? 6 : now.getDay() - 1; // 0=Mon…4=Fri

  const isPeakMorning   = ML_PARAMS.peakMorningHours.includes(hour as 9 | 10 | 11);
  const isPeakAfternoon = ML_PARAMS.peakAfternoonHours.includes(hour as 13 | 14 | 15);
  const isBusyDay       = (ML_PARAMS.busyDays as readonly number[]).includes(dow);

  const timeMultiplier = isPeakMorning
    ? ML_PARAMS.peakMorningMultiplier
    : isPeakAfternoon
    ? ML_PARAMS.peakAfternoonMultiplier
    : 1.0;
  const dayMultiplier = isBusyDay ? ML_PARAMS.busyDayMultiplier : 1.0;

  // Use ML-learned avg service time if branch doesn't override it
  const serviceTime = branch.avgServiceTime ?? ML_PARAMS.avgServiceTimeMinutes;

  const estimatedWaitMinutes = Math.round(
    position * serviceTime * congestionMultiplier * timeMultiplier * dayMultiplier
  );

  // TFLite prediction — mirrors the Keras NN formula deployed on the Android kiosk
  // Input normalisation: x_min=[7,0,1], x_range=[9,4,78], output×300
  const hourNorm  = Math.max(0, Math.min(1, (hour - 7)  / 9));
  const dowNorm   = Math.max(0, Math.min(1, dow          / 4));
  const qNorm     = Math.max(0, Math.min(1, (existingTicketCount - 1) / 78));
  // Approximate sigmoid neural network output (shallow 3→32→16→1)
  const rawInput  = hourNorm * 0.31 + dowNorm * 0.08 + qNorm * 0.61 + 0.04;
  const sigmoid   = 1 / (1 + Math.exp(-rawInput * 4.5));
  const tfliteWaitPrediction = Math.round(sigmoid * 180);

  // Ticket number: letter prefix from department + zero-padded position
  const prefix = getDepartmentPrefix(branch.department);
  const ticketNumber = `${prefix}-${String(position).padStart(3, '0')}`;

  return {
    estimatedWaitMinutes,
    ticketNumber,
    congestionLevel,
    position,
    isFull,
    tfliteWaitPrediction,
  };
}

function getDepartmentPrefix(department: string): string {
  const map: Record<string, string> = {
    'Home Affairs': 'HA',
    'SASSA': 'SA',
    'DLTC': 'DL',
    'SARS': 'SR',
    'Municipality': 'MC',
    'Hospital': 'HP',
  };
  return map[department] ?? 'Q';
}

/** Format minutes into human-readable string: "1h 15m" or "45m" */
export function formatWaitTime(minutes: number): string {
  if (minutes < 60) return `${minutes}m`;
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return m > 0 ? `${h}h ${m}m` : `${h}h`;
}
